// Generated by Selenium IDE
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeAll;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

import static org.junit.jupiter.api.Assertions.assertEquals;
public class SeleniumAllTestCases {

    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @BeforeAll
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        System.setProperty("webdriver.chrome.driver", "E:\\Lab works\\6th Semester\\Testing_QA\\chromedriver-win64\\chromedriver.exe");
        vars = new HashMap<String, Object>();
    }
    @AfterAll
    public void tearDown() {
        driver.quit();
    }

    @AfterEach
    public void refreshPage(){
        driver.navigate().refresh();
    }

    @Test
    public void validlogin() {
        driver.get("https://practicesoftwaretesting.com/#/auth/login");
        driver.manage().window().setSize(new Dimension(1552, 840));
        driver.findElement(By.cssSelector("*[data-test=\"email\"]")).click();
        driver.findElement(By.cssSelector("*[data-test=\"email\"]")).sendKeys("customer@practicesoftwaretesting.com");
        driver.findElement(By.cssSelector("*[data-test=\"password\"]")).click();
        driver.findElement(By.cssSelector("*[data-test=\"password\"]")).sendKeys("welcome01");
        driver.findElement(By.cssSelector("*[data-test=\"login-submit\"]")).click();
        wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//*[@id=\"menu\"]")));
        String actualUrl=chrome.getCurrentUrl();
        String expectedUrl="https://practicesoftwaretesting.com/#/account";
        assertEquals(expectedUrl,actualUrl);
    }
    @Test
    public void invalidPass() {
        driver.get("https://practicesoftwaretesting.com/#/auth/login");
        driver.manage().window().setSize(new Dimension(1552, 840));
        driver.findElement(By.cssSelector("*[data-test=\"email\"]")).click();
        driver.findElement(By.cssSelector("*[data-test=\"email\"]")).sendKeys("customer@practicesoftwaretesting.com");
        driver.findElement(By.cssSelector("*[data-test=\"password\"]")).click();
        driver.findElement(By.cssSelector("*[data-test=\"password\"]")).sendKeys("abc");
        driver.findElement(By.cssSelector("*[data-test=\"login-submit\"]")).click();
        WebElement element=wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("/html/body/app-root/div/app-login/div/div/div/form/div[4]/div")));
        String expected="Invalid email or password";
        String actual=element.getText();
        assertEquals(expected,actual);
    }
    @Test
    public void invalidEmail() {
        driver.get("https://practicesoftwaretesting.com/#/auth/login");
        driver.manage().window().setSize(new Dimension(1552, 840));
        driver.findElement(By.cssSelector("*[data-test=\"email\"]")).click();
        driver.findElement(By.cssSelector("*[data-test=\"email\"]")).sendKeys("abc@gmail.com");
        driver.findElement(By.cssSelector("*[data-test=\"password\"]")).click();
        driver.findElement(By.cssSelector("*[data-test=\"password\"]")).click();
        driver.findElement(By.cssSelector("*[data-test=\"password\"]")).sendKeys("welcome01");
        driver.findElement(By.cssSelector("*[data-test=\"login-submit\"]")).click();
        WebElement element=wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("/html/body/app-root/div/app-login/div/div/div/form/div[4]/div")));
        String expected="Invalid email or password";
        String actual=element.getText();
        assertEquals(expected,actual);
    }
    @Test
    public void emptyPass() {
        driver.get("https://practicesoftwaretesting.com/#/auth/login");
        driver.manage().window().setSize(new Dimension(1552, 840));
        driver.findElement(By.cssSelector("*[data-test=\"email\"]")).click();
        driver.findElement(By.cssSelector("*[data-test=\"email\"]")).sendKeys("customer@practicesoftwaretesting.com");
        driver.findElement(By.cssSelector("*[data-test=\"login-submit\"]")).click();
        WebElement element=wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("/html/body/app-root/div/app-login/div/div/div/form/div[3]/div")));
        String expected="Password is required.";
        String actual=element.getText();
        assertEquals(expected,actual);
    }
    @Test
    public void emptyEmail() {
        driver.get("https://practicesoftwaretesting.com/#/auth/login");
        driver.manage().window().setSize(new Dimension(1552, 840));
        driver.findElement(By.cssSelector("*[data-test=\"password\"]")).click();
        driver.findElement(By.cssSelector("*[data-test=\"password\"]")).sendKeys("welcome01");
        driver.findElement(By.cssSelector("*[data-test=\"login-submit\"]")).click();
        WebElement element=wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("/html/body/app-root/div/app-login/div/div/div/form/div[2]/div")));
        String expected="E-mail is required.";
        String actual=element.getText();
        assertEquals(expected,actual);
    }

    @Test
    public void productDetails() {
        driver.get("https://practicesoftwaretesting.com/#/auth/login");
        driver.manage().window().setSize(new Dimension(1552, 840));
        driver.findElement(By.cssSelector("*[data-test=\"email\"]")).click();
        driver.findElement(By.cssSelector("*[data-test=\"email\"]")).sendKeys("customer@practicesoftwaretesting.com");
        driver.findElement(By.cssSelector("*[data-test=\"password\"]")).click();
        driver.findElement(By.cssSelector("*[data-test=\"password\"]")).sendKeys("welcome01");
        driver.findElement(By.cssSelector("*[data-test=\"login-submit\"]")).click();
        driver.findElement(By.cssSelector("*[data-test=\"nav-home\"]")).click();
        {
            WebElement element = driver.findElement(By.cssSelector("*[data-test=\"nav-home\"]"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        {
            WebElement element = driver.findElement(By.tagName("body"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element, 0, 0).perform();
        }
        driver.findElement(By.cssSelector(".card:nth-child(3) .card-img-top")).click();
        driver.findElement(By.cssSelector("*[data-test=\"increase-quantity\"]")).click();
        driver.findElement(By.cssSelector(".fa-minus")).click();
        driver.findElement(By.cssSelector("*[data-test=\"add-to-cart\"]")).click();
        driver.findElement(By.cssSelector("*[data-test=\"add-to-favorites\"]")).click();
    }

    @Test
    public void contact() {
        driver.get("https://practicesoftwaretesting.com/#/contact");
        driver.manage().window().setSize(new Dimension(1552, 840));
        driver.findElement(By.cssSelector("*[data-test=\"first-name\"]")).click();
        driver.findElement(By.cssSelector("*[data-test=\"first-name\"]")).sendKeys("Jane");
        driver.findElement(By.cssSelector("*[data-test=\"last-name\"]")).click();
        driver.findElement(By.cssSelector("*[data-test=\"last-name\"]")).sendKeys("Doe");
        driver.findElement(By.cssSelector("*[data-test=\"email\"]")).click();
        driver.findElement(By.cssSelector("*[data-test=\"email\"]")).sendKeys("customer@practicesoftwaretesting.com");
        driver.findElement(By.cssSelector("*[data-test=\"subject\"]")).click();
        {
            WebElement dropdown = driver.findElement(By.cssSelector("*[data-test=\"subject\"]"));
            dropdown.findElement(By.xpath("//option[. = 'Payments']")).click();
        }
        driver.findElement(By.cssSelector("*[data-test=\"message\"]")).click();
        driver.findElement(By.cssSelector("*[data-test=\"message\"]")).sendKeys("vsnovubnsvkjbskvhbbksdfvbkhfbvkjbfdkjvbdkjvbkjdfbvkjbdfkvjbdjkfvbkjbkvfjdbjkdfv");
        driver.findElement(By.cssSelector("*[data-test=\"contact-submit\"]")).click();
    }

    @Test
    public void sortA2Z() {
        driver.get("https://practicesoftwaretesting.com/#/");
        driver.manage().window().setSize(new Dimension(1552, 840));
        driver.findElement(By.cssSelector("*[data-test=\"sort\"]")).click();
        {
            WebElement dropdown = driver.findElement(By.cssSelector("*[data-test=\"sort\"]"));
            dropdown.findElement(By.xpath("//option[. = 'Name (A - Z)']")).click();
        }
    }
    @Test
    public void sortZ2A() {
        driver.get("https://practicesoftwaretesting.com/#/");
        driver.manage().window().setSize(new Dimension(1552, 840));
        {
            WebElement element = driver.findElement(By.cssSelector("*[data-test=\"search-reset\"]"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        driver.findElement(By.cssSelector("*[data-test=\"sort\"]")).click();
        {
            WebElement dropdown = driver.findElement(By.cssSelector("*[data-test=\"sort\"]"));
            dropdown.findElement(By.xpath("//option[. = 'Name (Z - A)']")).click();
        }
        {
            WebElement element = driver.findElement(By.cssSelector(".card:nth-child(1) .card-img-top"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
    }
    @Test
    public void sortHigh2Low() {
        driver.get("https://practicesoftwaretesting.com/#/");
        driver.manage().window().setSize(new Dimension(1552, 840));
        driver.findElement(By.cssSelector("*[data-test=\"sort\"]")).click();
        {
            WebElement dropdown = driver.findElement(By.cssSelector("*[data-test=\"sort\"]"));
            dropdown.findElement(By.xpath("//option[. = 'Price (High - Low)']")).click();
        }
    }
    @Test
    public void sortLow2High() {
        driver.get("https://practicesoftwaretesting.com/#/");
        driver.manage().window().setSize(new Dimension(1552, 840));
        driver.findElement(By.cssSelector("*[data-test=\"sort\"]")).click();
        {
            WebElement dropdown = driver.findElement(By.cssSelector("*[data-test=\"sort\"]"));
            dropdown.findElement(By.xpath("//option[. = 'Price (Low - High)']")).click();
        }
    }
    @Test
    public void filterByBrandForgeFlex() {
        driver.get("https://practicesoftwaretesting.com/#/");
        driver.manage().window().setSize(new Dimension(1552, 840));
        js.executeScript("window.scrollTo(0,399.20001220703125)");
        driver.findElement(By.cssSelector("*[data-test=\"brand-01HVZQ8YWVRJ58GK4RFNM380K8\"]")).click();
    }
    @Test
    public void filterByBrandMightyCraft() {
        driver.get("https://practicesoftwaretesting.com/#/");
        driver.manage().window().setSize(new Dimension(1552, 840));
        js.executeScript("window.scrollTo(0,74.4000015258789)");
        js.executeScript("window.scrollTo(0,268.79998779296875)");
        driver.findElement(By.cssSelector("*[data-test=\"brand-01HVZQ8YWVRJ58GK4RFNM380K9\"]")).click();
    }
    @Test
    public void filterByCategoryHandtools() {
        driver.get("https://practicesoftwaretesting.com/#/");
        driver.manage().window().setSize(new Dimension(1552, 840));
        js.executeScript("window.scrollTo(0,390.3999938964844)");
        driver.findElement(By.cssSelector("*[data-test=\"category-01HVZQ8YX3PYA0HV95XD3FYJ12\"]")).click();
    }
    @Test
    public void filterByCategoryPowerTools() {
        driver.get("https://practicesoftwaretesting.com/#/");
        driver.manage().window().setSize(new Dimension(1552, 840));
        js.executeScript("window.scrollTo(0,336)");
        driver.findElement(By.cssSelector("*[data-test=\"category-01HVZQ8YX3PYA0HV95XD3FYJ13\"]")).click();
    }
    @Test
    public void filterByCategoryWorkBench() {
        driver.get("https://practicesoftwaretesting.com/#/");
        driver.manage().window().setSize(new Dimension(1552, 840));
        js.executeScript("window.scrollTo(0,355.20001220703125)");
        driver.findElement(By.cssSelector("*[data-test=\"category-01HVZQ8YX7PJJP0C9C88Y60XJF\"]")).click();
        driver.findElement(By.cssSelector("app-root")).click();
    }
    @Test
    public void filterByCategoryWrench() {
        driver.get("https://practicesoftwaretesting.com/#/");
        driver.manage().window().setSize(new Dimension(1552, 840));
        js.executeScript("window.scrollTo(0,182.39999389648438)");
        js.executeScript("window.scrollTo(0,882.4000244140625)");
        driver.findElement(By.cssSelector("*[data-test=\"category-01HVZQ8YX7PJJP0C9C88Y60XJ4\"]")).click();
    }
    @Test
    public void searchHammer() {
        driver.get("https://practicesoftwaretesting.com/#/");
        driver.manage().window().setSize(new Dimension(1552, 840));
        driver.findElement(By.cssSelector("*[data-test=\"search-query\"]")).click();
        driver.findElement(By.cssSelector("*[data-test=\"search-query\"]")).sendKeys("Hammer");
        driver.findElement(By.cssSelector("*[data-test=\"search-submit\"]")).click();
    }
    @Test
    public void searchPliers() {
        driver.get("https://practicesoftwaretesting.com/#/");
        driver.manage().window().setSize(new Dimension(1552, 840));
        js.executeScript("window.scrollTo(0,126.4000015258789)");
        driver.findElement(By.cssSelector("*[data-test=\"search-query\"]")).click();
        driver.findElement(By.cssSelector("*[data-test=\"search-query\"]")).sendKeys("Pliers");
        driver.findElement(By.cssSelector("*[data-test=\"search-submit\"]")).click();
    }
    @Test
    public void filterByPrice() {
        driver.get("https://practicesoftwaretesting.com/#/");
        driver.manage().window().setSize(new Dimension(1552, 840));
        {
            WebElement element = driver.findElement(By.cssSelector(".col-md-9"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).clickAndHold().perform();
        }
        {
            WebElement element = driver.findElement(By.cssSelector(".col-md-9"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        {
            WebElement element = driver.findElement(By.cssSelector(".col-md-9"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).release().perform();
        }
        driver.findElement(By.cssSelector(".row:nth-child(3)")).click();
        {
            WebElement element = driver.findElement(By.cssSelector(".ngx-slider-pointer-min"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).clickAndHold().perform();
        }
        {
            WebElement element = driver.findElement(By.cssSelector(".ngx-slider-pointer-min"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        {
            WebElement element = driver.findElement(By.cssSelector(".ngx-slider-pointer-min"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).release().perform();
        }
        driver.findElement(By.cssSelector(".ngx-slider-pointer-min")).click();
    }

    @Test
    public void profilePage() {
        driver.get("https://practicesoftwaretesting.com/#/auth/login");
        driver.manage().window().setSize(new Dimension(1552, 840));
        driver.findElement(By.cssSelector("*[data-test=\"email\"]")).click();
        driver.findElement(By.cssSelector("*[data-test=\"email\"]")).sendKeys("customer@practicesoftwaretesting.com");
        driver.findElement(By.cssSelector("*[data-test=\"password\"]")).click();
        driver.findElement(By.cssSelector("*[data-test=\"password\"]")).sendKeys("welcome01");
        driver.findElement(By.cssSelector("*[data-test=\"login-submit\"]")).click();
        driver.findElement(By.cssSelector(".fa-address-card")).click();
    }
    @Test
    public void buyNowPayLater() {
        driver.get("https://practicesoftwaretesting.com/#/auth/login");
        driver.manage().window().setSize(new Dimension(1552, 840));
        driver.findElement(By.cssSelector("*[data-test=\"email\"]")).click();
        driver.findElement(By.cssSelector("*[data-test=\"email\"]")).sendKeys("customer@practicesoftwaretesting.com");
        driver.findElement(By.cssSelector("*[data-test=\"password\"]")).click();
        driver.findElement(By.cssSelector("*[data-test=\"password\"]")).sendKeys("welcome01");
        driver.findElement(By.cssSelector("*[data-test=\"login-submit\"]")).click();
        driver.findElement(By.cssSelector("*[data-test=\"nav-home\"]")).click();
        driver.findElement(By.cssSelector(".card:nth-child(8) .card-img-top")).click();
        driver.findElement(By.cssSelector("*[data-test=\"add-to-cart\"]")).click();
        driver.findElement(By.cssSelector("*[data-test=\"cart-quantity\"]")).click();
        driver.findElement(By.cssSelector("*[data-test=\"proceed-1\"]")).click();
        driver.findElement(By.cssSelector("*[data-test=\"proceed-2\"]")).click();
        driver.findElement(By.cssSelector("*[data-test=\"state\"]")).click();
        driver.findElement(By.cssSelector("*[data-test=\"state\"]")).sendKeys("f");
        driver.findElement(By.cssSelector("*[data-test=\"postcode\"]")).click();
        driver.findElement(By.cssSelector("*[data-test=\"postcode\"]")).sendKeys("3");
        driver.findElement(By.cssSelector("*[data-test=\"proceed-3\"]")).click();
        driver.findElement(By.cssSelector("*[data-test=\"payment-method\"]")).click();
        {
            WebElement dropdown = driver.findElement(By.cssSelector("*[data-test=\"payment-method\"]"));
            dropdown.findElement(By.xpath("//option[. = 'Buy Now Pay Later']")).click();
        }
        driver.findElement(By.cssSelector("*[data-test=\"monthly_installments\"]")).click();
        {
            WebElement dropdown = driver.findElement(By.cssSelector("*[data-test=\"monthly_installments\"]"));
            dropdown.findElement(By.xpath("//option[. = '12 monthly installments']")).click();
        }
        driver.findElement(By.cssSelector("*[data-test=\"finish\"]")).click();
    }
    @Test
    public void payWithCreditCard() {
        driver.get("https://practicesoftwaretesting.com/#/auth/login");
        driver.manage().window().setSize(new Dimension(1552, 840));
        driver.findElement(By.cssSelector("*[data-test=\"email\"]")).click();
        driver.findElement(By.cssSelector("*[data-test=\"email\"]")).sendKeys("customer@practicesoftwaretesting.com");
        driver.findElement(By.cssSelector("*[data-test=\"password\"]")).click();
        driver.findElement(By.cssSelector("*[data-test=\"password\"]")).sendKeys("welcome01");
        driver.findElement(By.cssSelector("*[data-test=\"login-submit\"]")).click();
        driver.findElement(By.cssSelector("*[data-test=\"nav-home\"]")).click();
        {
            WebElement element = driver.findElement(By.cssSelector(".card:nth-child(2) .card-img-top"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        {
            WebElement element = driver.findElement(By.tagName("body"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element, 0, 0).perform();
        }
        driver.findElement(By.cssSelector(".card:nth-child(9) .card-img-top")).click();
        driver.findElement(By.cssSelector("*[data-test=\"add-to-cart\"]")).click();
        {
            WebElement element = driver.findElement(By.cssSelector("*[data-test=\"nav-menu\"]"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        {
            WebElement element = driver.findElement(By.tagName("body"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element, 0, 0).perform();
        }
        driver.findElement(By.cssSelector(".nav-link > .fa")).click();
        {
            WebElement element = driver.findElement(By.cssSelector("*[data-test=\"nav-menu\"]"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        driver.findElement(By.cssSelector("*[data-test=\"proceed-1\"]")).click();
        driver.findElement(By.cssSelector("*[data-test=\"proceed-2\"]")).click();
        driver.findElement(By.cssSelector("*[data-test=\"state\"]")).click();
        driver.findElement(By.cssSelector("*[data-test=\"state\"]")).sendKeys("c");
        driver.findElement(By.cssSelector("*[data-test=\"postcode\"]")).click();
        driver.findElement(By.cssSelector("*[data-test=\"postcode\"]")).sendKeys("2");
        driver.findElement(By.cssSelector("*[data-test=\"proceed-3\"]")).click();
        driver.findElement(By.cssSelector("*[data-test=\"payment-method\"]")).click();
        {
            WebElement dropdown = driver.findElement(By.cssSelector("*[data-test=\"payment-method\"]"));
            dropdown.findElement(By.xpath("//option[. = 'Credit Card']")).click();
        }
        driver.findElement(By.cssSelector("*[data-test=\"credit_card_number\"]")).click();
        driver.findElement(By.cssSelector("*[data-test=\"credit_card_number\"]")).sendKeys("0000-0000-0000-0000");
        driver.findElement(By.cssSelector("*[data-test=\"expiration_date\"]")).click();
        driver.findElement(By.cssSelector("*[data-test=\"expiration_date\"]")).sendKeys("09/2027");
        driver.findElement(By.cssSelector("*[data-test=\"cvv\"]")).click();
        driver.findElement(By.cssSelector("*[data-test=\"cvv\"]")).sendKeys("233");
        {
            WebElement element = driver.findElement(By.cssSelector("*[data-test=\"card_holder_name\"]"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).clickAndHold().perform();
        }
        {
            WebElement element = driver.findElement(By.cssSelector("*[data-test=\"card_holder_name\"]"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        {
            WebElement element = driver.findElement(By.cssSelector("*[data-test=\"card_holder_name\"]"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).release().perform();
        }
        driver.findElement(By.cssSelector("*[data-test=\"card_holder_name\"]")).click();
        driver.findElement(By.cssSelector("*[data-test=\"card_holder_name\"]")).sendKeys("tawfiq");
        driver.findElement(By.cssSelector("*[data-test=\"finish\"]")).click();
    }
    @Test
    public void favouritePage() {
        driver.get("https://practicesoftwaretesting.com/#/auth/login");
        driver.manage().window().setSize(new Dimension(1552, 840));
        driver.findElement(By.cssSelector("*[data-test=\"email\"]")).click();
        driver.findElement(By.cssSelector("*[data-test=\"email\"]")).sendKeys("customer@practicesoftwaretesting.com");
        driver.findElement(By.cssSelector("*[data-test=\"password\"]")).click();
        driver.findElement(By.cssSelector("*[data-test=\"password\"]")).sendKeys("welcome01");
        driver.findElement(By.cssSelector("*[data-test=\"login-submit\"]")).click();
        driver.findElement(By.cssSelector("*[data-test=\"nav-favorites\"]")).click();
    }


}
