// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class HomePageTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @BeforeAll
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    System.setProperty("webdriver.chrome.driver", "E:\\Lab works\\6th Semester\\Testing_QA\\chromedriver-win64\\chromedriver.exe");
    vars = new HashMap<String, Object>();
  }
  @AfterAll
  public void tearDown() {
    driver.quit();
  }

  @AfterEach
  public void refreshPage(){
      driver.navigate().refresh();
  }
  
  @Test
  public void sortA2Z() {
    driver.get("https://practicesoftwaretesting.com/#/");
    driver.manage().window().setSize(new Dimension(1552, 840));
    driver.findElement(By.cssSelector("*[data-test=\"sort\"]")).click();
    {
      WebElement dropdown = driver.findElement(By.cssSelector("*[data-test=\"sort\"]"));
      dropdown.findElement(By.xpath("//option[. = 'Name (A - Z)']")).click();
    }
  }
  @Test
  public void sortZ2A() {
    driver.get("https://practicesoftwaretesting.com/#/");
    driver.manage().window().setSize(new Dimension(1552, 840));
    {
      WebElement element = driver.findElement(By.cssSelector("*[data-test=\"search-reset\"]"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector("*[data-test=\"sort\"]")).click();
    {
      WebElement dropdown = driver.findElement(By.cssSelector("*[data-test=\"sort\"]"));
      dropdown.findElement(By.xpath("//option[. = 'Name (Z - A)']")).click();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".card:nth-child(1) .card-img-top"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
  }
  @Test
  public void sortHigh2Low() {
    driver.get("https://practicesoftwaretesting.com/#/");
    driver.manage().window().setSize(new Dimension(1552, 840));
    driver.findElement(By.cssSelector("*[data-test=\"sort\"]")).click();
    {
      WebElement dropdown = driver.findElement(By.cssSelector("*[data-test=\"sort\"]"));
      dropdown.findElement(By.xpath("//option[. = 'Price (High - Low)']")).click();
    }
  }
  @Test
  public void sortLow2High() {
    driver.get("https://practicesoftwaretesting.com/#/");
    driver.manage().window().setSize(new Dimension(1552, 840));
    driver.findElement(By.cssSelector("*[data-test=\"sort\"]")).click();
    {
      WebElement dropdown = driver.findElement(By.cssSelector("*[data-test=\"sort\"]"));
      dropdown.findElement(By.xpath("//option[. = 'Price (Low - High)']")).click();
    }
  }
  @Test
  public void filterByBrandForgeFlex() {
    driver.get("https://practicesoftwaretesting.com/#/");
    driver.manage().window().setSize(new Dimension(1552, 840));
    js.executeScript("window.scrollTo(0,399.20001220703125)");
    driver.findElement(By.cssSelector("*[data-test=\"brand-01HVZQ8YWVRJ58GK4RFNM380K8\"]")).click();
  }
  @Test
  public void filterByBrandMightyCraft() {
    driver.get("https://practicesoftwaretesting.com/#/");
    driver.manage().window().setSize(new Dimension(1552, 840));
    js.executeScript("window.scrollTo(0,74.4000015258789)");
    js.executeScript("window.scrollTo(0,268.79998779296875)");
    driver.findElement(By.cssSelector("*[data-test=\"brand-01HVZQ8YWVRJ58GK4RFNM380K9\"]")).click();
  }
  @Test
  public void filterByCategoryHandtools() {
    driver.get("https://practicesoftwaretesting.com/#/");
    driver.manage().window().setSize(new Dimension(1552, 840));
    js.executeScript("window.scrollTo(0,390.3999938964844)");
    driver.findElement(By.cssSelector("*[data-test=\"category-01HVZQ8YX3PYA0HV95XD3FYJ12\"]")).click();
  }
  @Test
  public void filterByCategoryPowerTools() {
    driver.get("https://practicesoftwaretesting.com/#/");
    driver.manage().window().setSize(new Dimension(1552, 840));
    js.executeScript("window.scrollTo(0,336)");
    driver.findElement(By.cssSelector("*[data-test=\"category-01HVZQ8YX3PYA0HV95XD3FYJ13\"]")).click();
  }
  @Test
  public void filterByCategoryWorkBench() {
    driver.get("https://practicesoftwaretesting.com/#/");
    driver.manage().window().setSize(new Dimension(1552, 840));
    js.executeScript("window.scrollTo(0,355.20001220703125)");
    driver.findElement(By.cssSelector("*[data-test=\"category-01HVZQ8YX7PJJP0C9C88Y60XJF\"]")).click();
    driver.findElement(By.cssSelector("app-root")).click();
  }
  @Test
  public void filterByCategoryWrench() {
    driver.get("https://practicesoftwaretesting.com/#/");
    driver.manage().window().setSize(new Dimension(1552, 840));
    js.executeScript("window.scrollTo(0,182.39999389648438)");
    js.executeScript("window.scrollTo(0,882.4000244140625)");
    driver.findElement(By.cssSelector("*[data-test=\"category-01HVZQ8YX7PJJP0C9C88Y60XJ4\"]")).click();
  }
  @Test
  public void searchHammer() {
    driver.get("https://practicesoftwaretesting.com/#/");
    driver.manage().window().setSize(new Dimension(1552, 840));
    driver.findElement(By.cssSelector("*[data-test=\"search-query\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"search-query\"]")).sendKeys("Hammer");
    driver.findElement(By.cssSelector("*[data-test=\"search-submit\"]")).click();
  }
  @Test
  public void searchPliers() {
    driver.get("https://practicesoftwaretesting.com/#/");
    driver.manage().window().setSize(new Dimension(1552, 840));
    js.executeScript("window.scrollTo(0,126.4000015258789)");
    driver.findElement(By.cssSelector("*[data-test=\"search-query\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"search-query\"]")).sendKeys("Pliers");
    driver.findElement(By.cssSelector("*[data-test=\"search-submit\"]")).click();
  }
  @Test
  public void filterByPrice() {
    driver.get("https://practicesoftwaretesting.com/#/");
    driver.manage().window().setSize(new Dimension(1552, 840));
    {
      WebElement element = driver.findElement(By.cssSelector(".col-md-9"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".col-md-9"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".col-md-9"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector(".row:nth-child(3)")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".ngx-slider-pointer-min"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".ngx-slider-pointer-min"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".ngx-slider-pointer-min"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector(".ngx-slider-pointer-min")).click();
  }
  @Test
  public void searchbar() {
    driver.get("https://practicesoftwaretesting.com/");
    driver.manage().window().setSize(new Dimension(1936, 1056));
    driver.findElement(By.cssSelector("*[data-test=\"search-query\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"search-query\"]")).sendKeys("Bolt Cutters");
    driver.findElement(By.cssSelector("*[data-test=\"search-submit\"]")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("*[data-test=\"search-submit\"]"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
  }
}
